configured_endpoints: 18
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/fragment-foundries-inc-dash%2Ffragment-ac78ba9cc0f791a7f2f6a9e3f9e06c325c32f5267f01f2a5467c5d2ffa0a4af5.yml
openapi_spec_hash: d0e94de249cd9957056dedab4c6d76ef
config_hash: 4f6f1e36f224edbbd1e0620dce819b32
