/**
 * Jest setup file for mocking OAuth2 authentication.
 * This file is NOT generated by Stainless and won't be overwritten.
 *
 * The Fragment SDK uses OAuth2 client credentials flow which makes a request
 * to an external token endpoint. This mock ensures tests don't need a real
 * OAuth server.
 */

import Fragment from 'fragment';
import { buildHeaders } from 'fragment/internal/headers';

// Mock auth headers to return a static Bearer token
// This avoids the OAuth2 token fetch entirely
const originalAuthHeaders = (Fragment.prototype as any).authHeaders;

(Fragment.prototype as any).authHeaders = async function () {
  // Skip OAuth flow entirely and return mock auth header
  if (this.clientID && this.clientSecret) {
    return buildHeaders([{ Authorization: 'Bearer mock_access_token' }]);
  }
  return undefined;
};
